### ISSUE TITLE
[Localization of training material] I can't find the issue you opened

### ISSUE THREAD

**Issue by jibe-b** [manabuishii/galaxy-translation#12]
Dear @manabuishii, I would like to contribute to the discussion around the localization of Galaxy training material but I can't find it. May I ask you in which repository you opened it?

Best regards,

Jibé

**Comment by manabuishii** [comment]
I just create issue.

https://github.com/galaxyproject/training-material/issues/404

**Comment by jibe-b** [comment]
Great, ありがとうございました!
